### PR TITLE
Added splash screen. Testing required.

### PR DESCRIPTION
**Pull request by RudrakshK**
Issue #2 . I have added a splash screen in accordance with the color scheme and the font that the app uses. Testing is required. If it breaks let me know.

### CODE REVIEW

**Comment by kshitij86** [comment]
@RudrakshK looks like it renders properly. Could you please make the 'W' in logo lowercase as well? Because that's what we're following.

**Comment by RudrakshK** [comment]
I have updated the logo with the aforementioned changes.

**Review by kshitij86 — APPROVED** [review]
Looks great! Nice Job!

**Comment by kshitij86** [comment]
@RudrakshK Thanks for your contribution! Don't forget to star the repository and open any new issues you feel are relevant.
Happy Hacktoberfest !

**Comment by RudrakshK** [comment]
Thank you!

**Pull request merged**
